"""empty message

Revision ID: 49c427139f95
Revises: 0d54dd50235f
Create Date: 2017-04-07 18:52:51.394870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49c427139f95'
down_revision = '0d54dd50235f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wish',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('thumbnail', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('users_wishes',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('wish_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ),
    sa.ForeignKeyConstraint(['wish_id'], ['wish.item_id'], )
    )
    op.add_column(u'user_profile', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column(u'user_profile', sa.Column('created_on', sa.String(length=80), nullable=True))
    op.add_column(u'user_profile', sa.Column('gender', sa.String(length=1), nullable=True))
    op.add_column(u'user_profile', sa.Column('image', sa.String(length=255), nullable=True))
    op.add_column(u'user_profile', sa.Column('name', sa.String(length=80), nullable=True))
    op.drop_column(u'user_profile', 'first_name')
    op.drop_column(u'user_profile', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'user_profile', sa.Column('last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column(u'user_profile', sa.Column('first_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column(u'user_profile', 'name')
    op.drop_column(u'user_profile', 'image')
    op.drop_column(u'user_profile', 'gender')
    op.drop_column(u'user_profile', 'created_on')
    op.drop_column(u'user_profile', 'age')
    op.drop_table('users_wishes')
    op.drop_table('wish')
    # ### end Alembic commands ###
